export const theme = {
    colors: {
      primary: ['#FFE5D9', '#FFD7C9', '#FFC9B9'],
      quiz: ['#E8F4FF', '#D4E9FF', '#C0DFFF'],
      success: '#4CAF50',
      error: '#F44336',
      warning: '#FF9800',
      textDark: '#4A4A4A',
      textMedium: '#6A6A6A',
      textLight: '#8A8A8A',
      white: '#FFFFFF',
      background: '#F5F5F5',
    },
    spacing: {
      xs: 4,
      sm: 8,
      md: 16,
      lg: 24,
      xl: 32,
    },
    borderRadius: {
      sm: 8,
      md: 12,
      lg: 16,
      xl: 20,
    },
    fontSize: {
      xs: 12,
      sm: 14,
      md: 16,
      lg: 18,
      xl: 24,
      xxl: 32,
    },
  };